twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 25
      manual:
        topic   : manual_cmd_vel
        timeout : 0.5
        priority: 50
