<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arsenal_navigator</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="n0sc3tipsum@todo.todo">n0sc3tipsum</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>os</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>joint_state_publisher</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>
  <depend>std_msgs</depend>
  <depend>rviz</depend>
  <depend>control_msgs</depend>
  <depend>control_toolbox</depend>
  <depend>controller_interface</depend>
  <depend>controller_manager</depend>
  <depend>controller_manager_msgs</depend>
  <depend>slam_toolbox</depend>
  <depend>navigation2</depend>
  <depend>gazebo</depend>
  <depend>tf_transformations</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>topic_based_ros2_control</depend>
  <depend>robot_localization</depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
